### ISSUE TITLE
Strafe Mk2 Logo Not exposed by SDK

### ISSUE THREAD

**Issue by MayhemBill** [CorsairOfficial/cue-sdk#19]
I recently started using a software called Artemis, (to control both my Razer and Corsair periphs) unfortunately it would seem that the logo on the Strafe Mk2 isn't exposed by the sdk, and therefore cannot be controlled by Artemis.

Would it be possible to amend the logo to the sdk?

**Comment by intrueder** [comment]
I just installed the latest available version of Artemis, it turns out that Artemis is using an outdated version of CUESDK v3.0.301, while CUESDK v3.0.361 is available (here https://github.com/CorsairOfficial/cue-sdk/releases)

Updating CUESDK to the latest version should help. Please, contact Artemis developers.

**Comment by MayhemBill** [comment]
Sorry for the late reply, I talked with Spoinky (Artemis Developer) and the corsair sdk was updated a few days ago and the issue is still there.

**Comment by intrueder** [comment]
Will be fixed on RGB.NET side: https://github.com/DarthAffe/RGB.NET/issues/210
Related: #25
